on:
    push:
      branches:
        - example
    # pull_request:
    #   branches:
    #     - example
    workflow_dispatch:
permissions:
    id-token: write
    contents: read
env:
  AWS_REGION : "us-west-2"
name: deploy_terraform_examples
jobs:
  TerraformModuleTest:
    strategy:
          matrix:
            stack: ["eks_cluster_basic"]
    runs-on: ubuntu-latest
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::619184238146:role/github-devops-provisioner
        role-session-name: samplerolesessio
        aws-region: ${{ env.AWS_REGION }}
    - name:  Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.3"

    - name: Terraform init
      run: |
        cd examples/${{ matrix.stack }}
        ls
        terraform version
        terraform init

    - name: Terraform plan
      id: plan
      run: |
        terraform plan -no-color

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}
